# Generated by Django 3.0.5 on 2020-04-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(default='', max_length=20)),
                ('Gold_Price', models.CharField(default='10000', max_length=32)),
                ('Platinum_Price', models.CharField(default='10000', max_length=32)),
                ('Silver_Price', models.CharField(default='10000', max_length=32)),
                ('Diamond_Price', models.CharField(default='10000', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemId', models.CharField(max_length=32)),
                ('WeightInGram', models.CharField(max_length=32)),
                ('TotalPrice', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='shopcustomers',
            old_name='FirstName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='shopcustomers',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='shopcustomers',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='shopcustomers',
            name='LastName',
        ),
        migrations.AlterField(
            model_name='shopcustomers',
            name='PhoneNumber',
            field=models.CharField(help_text='Phone Number', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='shophandlerssignup',
            name='Alt_PhoneNumber',
            field=models.CharField(help_text='Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='shophandlerssignup',
            name='PhoneNumber',
            field=models.CharField(help_text='Phone Number', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='shophandlerssignup',
            name='ShopHandlers_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ChitBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers')),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_id', models.CharField(max_length=64)),
                ('Making_Charge', models.CharField(max_length=64)),
                ('Wastage', models.CharField(max_length=64)),
                ('Weight', models.CharField(choices=[('961', '961'), ('Ordinary', 'Ordinary')], max_length=64)),
                ('Item_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=64)),
                ('Discount', models.CharField(max_length=64)),
                ('Payment_Mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=64)),
                ('Advance', models.CharField(max_length=64)),
                ('Cash', models.CharField(max_length=64)),
                ('Card', models.CharField(max_length=64)),
                ('Card_Holder', models.CharField(max_length=64)),
                ('Card_Amount', models.CharField(max_length=64)),
                ('Online_Transfer_UPI', models.CharField(max_length=64)),
                ('Online_Amount', models.CharField(max_length=64)),
                ('Chit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64)),
                ('Chit_Amount', models.CharField(max_length=64)),
                ('Balance', models.CharField(max_length=64)),
                ('Previous_Balance', models.CharField(max_length=64)),
                ('Total_Balance', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers')),
            ],
        ),
    ]
