# Generated by Django 3.0.5 on 2020-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20200421_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpricing',
            name='Diamond_Price',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='materialpricing',
            name='Gold_Price',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='materialpricing',
            name='Platinum_Price',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='materialpricing',
            name='Silver_Price',
            field=models.CharField(default='', max_length=32),
        ),
    ]
