# Generated by Django 3.0.5 on 2020-04-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20200423_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Date',
            field=models.CharField(default='', max_length=32),
        ),
    ]
