# Generated by Django 3.0.5 on 2020-04-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_billingdetails_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='Bill_No',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='Bill_Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopHandlersSignUp'),
        ),
    ]
