# Generated by Django 3.0.5 on 2020-04-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20200424_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='Item_id',
            field=models.CharField(default='[]', max_length=64),
        ),
    ]
