# Generated by Django 3.0.5 on 2020-04-28 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_auto_20200428_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_No', models.CharField(default='', max_length=1024)),
                ('Item_id', models.CharField(default='[]', max_length=64)),
                ('Making_Charge', models.CharField(max_length=64)),
                ('Wastage', models.CharField(max_length=64)),
                ('Item_type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=64)),
                ('Date', models.CharField(default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers')),
            ],
        ),
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=64)),
                ('Advance', models.CharField(max_length=64)),
                ('Cash', models.CharField(max_length=64)),
                ('Card', models.CharField(max_length=64)),
                ('Card_Holder', models.CharField(max_length=64)),
                ('Card_Amount', models.CharField(max_length=64)),
                ('Online_Transfer_UPI', models.CharField(max_length=64)),
                ('Online_Amount', models.CharField(max_length=64)),
                ('Chit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64)),
                ('Chit_Amount', models.CharField(max_length=64)),
                ('Balance', models.CharField(max_length=64)),
                ('Previous_Balance', models.CharField(max_length=64)),
                ('Total_Balance', models.CharField(max_length=64)),
                ('Bill_Person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopHandlersSignUp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.BillingItems')),
            ],
        ),
    ]
