# Generated by Django 3.0.5 on 2020-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_billingitems_billingpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Item_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='[]', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Making_Charge',
            field=models.CharField(default='[]', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Wastage',
            field=models.CharField(default='[]', max_length=64),
        ),
    ]
