# Generated by Django 3.0.5 on 2020-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_auto_20200428_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Item_id',
            field=models.CharField(blank=True, default='[]', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Item_type',
            field=models.CharField(blank=True, default='[]', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Making_Charge',
            field=models.CharField(blank=True, default='[]', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Wastage',
            field=models.CharField(blank=True, default='[]', max_length=64, null=True),
        ),
    ]
