# Generated by Django 3.0.5 on 2020-04-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_auto_20200428_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitems',
            name='Total',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Date',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Item_id',
            field=models.CharField(blank=True, default='[]', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Item_type',
            field=models.CharField(blank=True, default='[]', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Making_Charge',
            field=models.CharField(blank=True, default='[]', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Wastage',
            field=models.CharField(blank=True, default='[]', max_length=2048, null=True),
        ),
    ]
