# Generated by Django 3.0.5 on 2020-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_auto_20200429_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitems',
            name='Total_Amount_PreBill',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Total',
            field=models.CharField(default='[]', max_length=2048),
        ),
    ]
