# Generated by Django 3.0.5 on 2020-04-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_auto_20200429_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Total_Amount_PreBill',
            field=models.CharField(default='2020-04-29', max_length=64),
        ),
    ]
