# Generated by Django 3.0.5 on 2020-04-29 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_auto_20200429_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Total_Amount_PreBill',
            field=models.CharField(default=datetime.date(2020, 4, 29), max_length=64),
        ),
    ]
