# Generated by Django 3.0.5 on 2020-04-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_auto_20200429_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Date',
            field=models.DateField(default='2020-29-04'),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='Total_Amount_PreBill',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
