# Generated by Django 3.0.5 on 2020-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_auto_20200429_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestock',
            name='ItemId',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
