# Generated by Django 3.0.5 on 2020-04-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_auto_20200430_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcestock',
            old_name='ItemId',
            new_name='Item_ID',
        ),
        migrations.RenameField(
            model_name='resourcestock',
            old_name='TotalPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='resourcestock',
            old_name='WeightInGram',
            new_name='Weight_In_Grams',
        ),
    ]
