# Generated by Django 3.0.5 on 2020-04-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_auto_20200430_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcestock',
            old_name='Item_ID',
            new_name='Item_Id',
        ),
    ]
