# Generated by Django 3.0.5 on 2020-04-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_auto_20200430_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestock',
            name='Item_Id',
            field=models.CharField(max_length=32),
        ),
    ]
