# Generated by Django 3.0.5 on 2020-04-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_auto_20200430_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcestock',
            name='Item_Id',
        ),
        migrations.AddField(
            model_name='resourcestock',
            name='ID',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='resourcestock',
            name='Price',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='resourcestock',
            name='Weight_In_Grams',
            field=models.CharField(default='', max_length=32),
        ),
    ]
