# Generated by Django 3.0.5 on 2020-04-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_auto_20200430_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcestock',
            old_name='ID',
            new_name='Stock_Id',
        ),
    ]
