# Generated by Django 3.0.5 on 2020-04-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_auto_20200430_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcestock',
            old_name='Stock_Id',
            new_name='Item_id',
        ),
    ]
