# Generated by Django 3.0.5 on 2020-04-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_auto_20200430_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceStock',
            new_name='Stock',
        ),
    ]
