# Generated by Django 3.0.5 on 2020-05-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_auto_20200502_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dealer_Name', models.CharField(default='', max_length=32, unique=True)),
                ('Metal_Type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=16)),
                ('Weight', models.CharField(default='', max_length=128)),
                ('Payment_Mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=16)),
                ('Amount', models.CharField(default='', max_length=32)),
                ('Date', models.DateField(default='2020-05-03')),
            ],
        ),
        migrations.CreateModel(
            name='StockPaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=16)),
                ('Metal_grams', models.CharField(default='', max_length=64)),
                ('Balance', models.CharField(default='', max_length=64)),
                ('Dealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.StockAdd')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('kammal', 'kammal'), ('vangi', 'vangi'), ('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Ottiyanam', 'Ottiyanam'), ('Ring', 'Ring')], default='Ring', max_length=32),
        ),
        migrations.DeleteModel(
            name='BillingDetails',
        ),
    ]
