# Generated by Django 3.0.5 on 2020-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0029_auto_20200503_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('kammal', 'kammal'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('nethichuti', 'nethichuti'), ('Metti', 'Metti'), ('Kaapu', 'Kaapu'), ('Ring', 'Ring'), ('Mookuthi', 'Mookuthi'), ('Aaram', 'Aaram'), ('Necklace', 'Necklace'), ('vangi', 'vangi')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Dealer_Name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
