# Generated by Django 3.0.5 on 2020-05-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0030_auto_20200503_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadd',
            name='Payment_Mode',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('kammal', 'kammal'), ('Ottiyanam', 'Ottiyanam'), ('chain', 'chain'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Aaram', 'Aaram'), ('Kaapu', 'Kaapu'), ('nethichuti', 'nethichuti'), ('Ring', 'Ring'), ('vangi', 'vangi'), ('Necklace', 'Necklace'), ('Mookuthi', 'Mookuthi')], default='Ring', max_length=32),
        ),
    ]
