# Generated by Django 3.0.5 on 2020-05-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0031_auto_20200503_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpaid',
            name='Amount_Paid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Ottiyanam', 'Ottiyanam'), ('kammal', 'kammal'), ('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('nethichuti', 'nethichuti'), ('ArnaKayiru', 'ArnaKayiru'), ('Bracelet', 'Bracelet'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('Aaram', 'Aaram'), ('Bangles', 'Bangles'), ('chain', 'chain')], default='Ring', max_length=32),
        ),
    ]
