# Generated by Django 3.0.5 on 2020-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0032_auto_20200503_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('kammal', 'kammal'), ('Ring', 'Ring'), ('nethichuti', 'nethichuti'), ('vangi', 'vangi'), ('Ottiyanam', 'Ottiyanam'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('Kaapu', 'Kaapu'), ('Aaram', 'Aaram'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Bangles', 'Bangles')], default='Ring', max_length=32),
        ),
    ]
