# Generated by Django 3.0.5 on 2020-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0033_auto_20200503_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadd',
            name='Nature',
            field=models.CharField(choices=[('916', '916'), ('Ordinary', 'Ordinary')], default='916', max_length=8),
        ),
        migrations.AddField(
            model_name='stockpaid',
            name='Payment_Date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Choice',
            field=models.CharField(choices=[('916', '916'), ('Ordinary', 'Ordinary')], default='961', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('ArnaKayiru', 'ArnaKayiru'), ('kammal', 'kammal'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('Bracelet', 'Bracelet'), ('vangi', 'vangi'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('nethichuti', 'nethichuti'), ('Ring', 'Ring'), ('Kaapu', 'Kaapu'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('Necklace', 'Necklace')], default='Ring', max_length=32),
        ),
    ]
