# Generated by Django 3.0.5 on 2020-05-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0035_auto_20200503_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('vangi', 'vangi'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Anklets', 'Anklets'), ('Mookuthi', 'Mookuthi'), ('Necklace', 'Necklace'), ('nethichuti', 'nethichuti'), ('Metti', 'Metti'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Myapp.StockAdd'),
        ),
    ]
