# Generated by Django 3.0.5 on 2020-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0036_auto_20200503_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('kammal', 'kammal'), ('ArnaKayiru', 'ArnaKayiru'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Ottiyanam', 'Ottiyanam'), ('Kaapu', 'Kaapu'), ('Mookuthi', 'Mookuthi'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Aaram', 'Aaram'), ('Necklace', 'Necklace'), ('chain', 'chain'), ('Ring', 'Ring'), ('nethichuti', 'nethichuti'), ('Metti', 'Metti')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-03'),
        ),
    ]
