# Generated by Django 3.0.5 on 2020-05-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0037_auto_20200503_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpaid',
            name='Payment_Date',
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('kammal', 'kammal'), ('Ottiyanam', 'Ottiyanam'), ('chain', 'chain'), ('Bangles', 'Bangles'), ('Aaram', 'Aaram'), ('nethichuti', 'nethichuti'), ('vangi', 'vangi'), ('Metti', 'Metti'), ('Kaapu', 'Kaapu'), ('Mookuthi', 'Mookuthi'), ('Necklace', 'Necklace'), ('Bracelet', 'Bracelet'), ('ArnaKayiru', 'ArnaKayiru'), ('Anklets', 'Anklets'), ('Ring', 'Ring')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-04'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-04'),
        ),
    ]
