# Generated by Django 3.0.5 on 2020-05-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0038_auto_20200504_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadd',
            name='Stock_No',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Ring', 'Ring'), ('vangi', 'vangi'), ('nethichuti', 'nethichuti'), ('chain', 'chain')], default='Ring', max_length=32),
        ),
    ]
