# Generated by Django 3.0.5 on 2020-05-05 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0039_auto_20200504_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Bracelet', 'Bracelet'), ('Mookuthi', 'Mookuthi'), ('Necklace', 'Necklace'), ('nethichuti', 'nethichuti'), ('Kaapu', 'Kaapu'), ('Anklets', 'Anklets'), ('Aaram', 'Aaram'), ('Bangles', 'Bangles'), ('kammal', 'kammal'), ('Metti', 'Metti'), ('Ring', 'Ring'), ('vangi', 'vangi'), ('chain', 'chain'), ('ArnaKayiru', 'ArnaKayiru'), ('Ottiyanam', 'Ottiyanam')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-05'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-05'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.StockAdd'),
        ),
    ]
