# Generated by Django 3.0.5 on 2020-05-05 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0040_auto_20200505_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Aaram', 'Aaram'), ('Bangles', 'Bangles'), ('Ottiyanam', 'Ottiyanam'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('ArnaKayiru', 'ArnaKayiru'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('nethichuti', 'nethichuti'), ('Metti', 'Metti'), ('Necklace', 'Necklace'), ('kammal', 'kammal'), ('Kaapu', 'Kaapu'), ('Mookuthi', 'Mookuthi'), ('chain', 'chain')], default='Ring', max_length=32),
        ),
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.CharField(default='', max_length=16)),
                ('Item_Type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=16)),
                ('Amount_Earned', models.CharField(default='', max_length=16)),
                ('Points_Earned', models.CharField(default='', max_length=16)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers')),
            ],
        ),
    ]
