# Generated by Django 3.0.5 on 2020-05-06 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0041_auto_20200505_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtable',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('Ottiyanam', 'Ottiyanam'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Bangles', 'Bangles'), ('vangi', 'vangi'), ('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Metti', 'Metti'), ('chain', 'chain'), ('nethichuti', 'nethichuti')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-06'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-06'),
        ),
    ]
