# Generated by Django 3.0.5 on 2020-05-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0042_auto_20200506_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Metti', 'Metti'), ('Anklets', 'Anklets'), ('kammal', 'kammal'), ('Ottiyanam', 'Ottiyanam'), ('Ring', 'Ring'), ('Mookuthi', 'Mookuthi'), ('Bracelet', 'Bracelet'), ('Aaram', 'Aaram'), ('Necklace', 'Necklace'), ('ArnaKayiru', 'ArnaKayiru'), ('chain', 'chain')], default='Ring', max_length=32),
        ),
    ]
