# Generated by Django 3.0.5 on 2020-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0043_auto_20200506_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Ring', 'Ring'), ('Mookuthi', 'Mookuthi'), ('nethichuti', 'nethichuti'), ('vangi', 'vangi'), ('chain', 'chain'), ('kammal', 'kammal'), ('Aaram', 'Aaram')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-08'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-08'),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metal_Type', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], max_length=16)),
                ('Given_Date', models.DateField(default='2020-05-08')),
                ('Delivery_Estimated_Date', models.DateField(default='2020-05-08')),
                ('Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Myapp.ShopCustomers')),
            ],
        ),
    ]
