# Generated by Django 3.0.5 on 2020-05-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0044_auto_20200508_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Phone_Number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Estimated_Date',
            field=models.DateField(default='2020-05-09'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.DateField(default='2020-05-09'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('nethichuti', 'nethichuti'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Metti', 'Metti'), ('Bracelet', 'Bracelet'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Anklets', 'Anklets'), ('kammal', 'kammal')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-09'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-09'),
        ),
    ]
