# Generated by Django 3.0.5 on 2020-05-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0045_auto_20200509_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('Ottiyanam', 'Ottiyanam'), ('kammal', 'kammal'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('nethichuti', 'nethichuti')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Metal_Type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=16),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('Ottiyanam', 'Ottiyanam'), ('kammal', 'kammal'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi'), ('nethichuti', 'nethichuti')], default='Ring', max_length=32),
        ),
    ]
