# Generated by Django 3.0.5 on 2020-05-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0046_auto_20200509_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Delivery_Status',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='repair',
            name='Repairing_Reason',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring'), ('Kaapu', 'Kaapu'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('nethichuti', 'nethichuti'), ('Bracelet', 'Bracelet'), ('vangi', 'vangi'), ('Metti', 'Metti'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Necklace', 'Necklace')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring'), ('Kaapu', 'Kaapu'), ('Ottiyanam', 'Ottiyanam'), ('Bangles', 'Bangles'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('nethichuti', 'nethichuti'), ('Bracelet', 'Bracelet'), ('vangi', 'vangi'), ('Metti', 'Metti'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Necklace', 'Necklace')], default='Ring', max_length=32),
        ),
    ]
