# Generated by Django 3.0.5 on 2020-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0047_auto_20200509_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Bill_No',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Aaram', 'Aaram'), ('Necklace', 'Necklace'), ('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Mookuthi', 'Mookuthi'), ('kammal', 'kammal'), ('Ottiyanam', 'Ottiyanam'), ('ArnaKayiru', 'ArnaKayiru'), ('chain', 'chain'), ('Bracelet', 'Bracelet'), ('Metti', 'Metti')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Aaram', 'Aaram'), ('Necklace', 'Necklace'), ('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Mookuthi', 'Mookuthi'), ('kammal', 'kammal'), ('Ottiyanam', 'Ottiyanam'), ('ArnaKayiru', 'ArnaKayiru'), ('chain', 'chain'), ('Bracelet', 'Bracelet'), ('Metti', 'Metti')], default='Ring', max_length=32),
        ),
    ]
