# Generated by Django 3.0.5 on 2020-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0048_auto_20200509_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Amount',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam'), ('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('Aaram', 'Aaram'), ('vangi', 'vangi'), ('kammal', 'kammal'), ('Metti', 'Metti'), ('ArnaKayiru', 'ArnaKayiru'), ('Anklets', 'Anklets'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('chain', 'chain'), ('nethichuti', 'nethichuti'), ('Bangles', 'Bangles'), ('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam'), ('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('Aaram', 'Aaram'), ('vangi', 'vangi'), ('kammal', 'kammal'), ('Metti', 'Metti'), ('ArnaKayiru', 'ArnaKayiru'), ('Anklets', 'Anklets'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring')], default='Ring', max_length=32),
        ),
    ]
