# Generated by Django 3.0.5 on 2020-05-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0049_auto_20200509_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='Total_Amount',
            field=models.CharField(default='[]', max_length=8),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Amount',
            field=models.CharField(default='[]', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Bill_No',
            field=models.CharField(default='[]', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Estimated_Date',
            field=models.DateField(default='[]'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Status',
            field=models.CharField(default='[]', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.DateField(default='[]'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Bracelet', 'Bracelet'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('chain', 'chain'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring'), ('nethichuti', 'nethichuti')], default='[]', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Metal_Type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='[]', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Repairing_Reason',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam'), ('Aaram', 'Aaram'), ('kammal', 'kammal'), ('Bracelet', 'Bracelet'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('chain', 'chain'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Ring', 'Ring'), ('nethichuti', 'nethichuti')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-10'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-10'),
        ),
    ]
