# Generated by Django 3.0.5 on 2020-05-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0050_auto_20200510_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='Amount',
            field=models.CharField(default='[]', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Estimated_Date',
            field=models.CharField(default='[]', max_length=64),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='[]', max_length=64),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('vangi', 'vangi'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Mookuthi', 'Mookuthi'), ('kammal', 'kammal'), ('chain', 'chain'), ('Aaram', 'Aaram'), ('Kaapu', 'Kaapu'), ('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam')], default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Metal_Type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Total_Amount',
            field=models.CharField(default='[]', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('vangi', 'vangi'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Mookuthi', 'Mookuthi'), ('kammal', 'kammal'), ('chain', 'chain'), ('Aaram', 'Aaram'), ('Kaapu', 'Kaapu'), ('Anklets', 'Anklets'), ('Necklace', 'Necklace'), ('Ottiyanam', 'Ottiyanam')], default='Ring', max_length=32),
        ),
    ]
