# Generated by Django 3.0.5 on 2020-05-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0051_auto_20200510_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='Amount',
            field=models.CharField(default='[]', max_length=128),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Bill_No',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Estimated_Date',
            field=models.CharField(default='[]', max_length=128),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.DateField(default='2020-05-10'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('Ottiyanam', 'Ottiyanam'), ('kammal', 'kammal'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Aaram', 'Aaram'), ('Mookuthi', 'Mookuthi'), ('chain', 'chain'), ('Necklace', 'Necklace'), ('ArnaKayiru', 'ArnaKayiru'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('Bracelet', 'Bracelet'), ('Metti', 'Metti'), ('Ring', 'Ring')], default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Metal_Type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='[]]', max_length=256),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Total_Amount',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('Ottiyanam', 'Ottiyanam'), ('kammal', 'kammal'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('Aaram', 'Aaram'), ('Mookuthi', 'Mookuthi'), ('chain', 'chain'), ('Necklace', 'Necklace'), ('ArnaKayiru', 'ArnaKayiru'), ('Bangles', 'Bangles'), ('Kaapu', 'Kaapu'), ('Bracelet', 'Bracelet'), ('Metti', 'Metti'), ('Ring', 'Ring')], default='Ring', max_length=32),
        ),
    ]
