# Generated by Django 3.0.5 on 2020-05-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0053_auto_20200510_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-10', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(choices=[('Bangles', 'Bangles'), ('Necklace', 'Necklace'), ('chain', 'chain'), ('Ring', 'Ring'), ('vangi', 'vangi'), ('nethichuti', 'nethichuti'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Metti', 'Metti'), ('kammal', 'kammal'), ('Bracelet', 'Bracelet'), ('Aaram', 'Aaram'), ('Ottiyanam', 'Ottiyanam'), ('Kaapu', 'Kaapu')], default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Bangles', 'Bangles'), ('Necklace', 'Necklace'), ('chain', 'chain'), ('Ring', 'Ring'), ('vangi', 'vangi'), ('nethichuti', 'nethichuti'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('Metti', 'Metti'), ('kammal', 'kammal'), ('Bracelet', 'Bracelet'), ('Aaram', 'Aaram'), ('Ottiyanam', 'Ottiyanam'), ('Kaapu', 'Kaapu')], default='Ring', max_length=32),
        ),
    ]
