# Generated by Django 3.0.5 on 2020-05-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0054_auto_20200510_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='Item_Type',
            field=models.CharField(default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Metal_Type',
            field=models.CharField(default='[]', max_length=256),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('chain', 'chain'), ('Bracelet', 'Bracelet'), ('Ring', 'Ring'), ('Kaapu', 'Kaapu'), ('Anklets', 'Anklets'), ('Metti', 'Metti'), ('ArnaKayiru', 'ArnaKayiru'), ('Mookuthi', 'Mookuthi'), ('vangi', 'vangi'), ('Bangles', 'Bangles'), ('Ottiyanam', 'Ottiyanam'), ('nethichuti', 'nethichuti'), ('kammal', 'kammal')], default='Ring', max_length=32),
        ),
    ]
