# Generated by Django 3.0.5 on 2020-05-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0055_auto_20200510_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('kammal', 'kammal'), ('chain', 'chain'), ('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('Ottiyanam', 'Ottiyanam'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi')], default='Ring', max_length=32),
        ),
    ]
