# Generated by Django 3.0.5 on 2020-05-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0056_auto_20200510_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='repair',
            name='OverallStatus',
            field=models.CharField(default='Not Delivered', max_length=16),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-11', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-11'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-11'),
        ),
    ]
