# Generated by Django 3.0.5 on 2020-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0057_auto_20200511_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Status',
            field=models.CharField(default='[]', max_length=256),
        ),
    ]
