# Generated by Django 3.0.5 on 2020-05-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0058_auto_20200511_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='OverallStatus',
        ),
        migrations.AlterField(
            model_name='repair',
            name='Delivery_Status',
            field=models.CharField(default='Not Delivered', max_length=16),
        ),
    ]
