# Generated by Django 3.0.5 on 2020-05-12 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0059_auto_20200511_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitbill',
            name='Address',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='chitbill',
            name='Amount',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='chitbill',
            name='Number_Of_Months',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='chitbill',
            name='Type_Of_Scheme',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly')], default='Weekly', max_length=32),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.ShopCustomers'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-12', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-12'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-12'),
        ),
    ]
