# Generated by Django 3.0.5 on 2020-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0060_auto_20200512_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitbill',
            old_name='Number_Of_Months',
            new_name='Number_Of_Months_or_Weeks',
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-13', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-13'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-13'),
        ),
    ]
