# Generated by Django 3.0.5 on 2020-05-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0061_auto_20200513_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitbill',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.ShopCustomers'),
        ),
    ]
