# Generated by Django 3.0.5 on 2020-05-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0062_auto_20200513_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitbill',
            name='Chit_No',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-13'),
        ),
        migrations.AddField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-13'),
        ),
    ]
