# Generated by Django 3.0.5 on 2020-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0064_auto_20200514_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitbillupdate',
            name='Status',
            field=models.CharField(default='On Going', max_length=16),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-16'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-16'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-16', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-16'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-16'),
        ),
    ]
