# Generated by Django 3.0.5 on 2020-05-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0065_auto_20200516_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Price',
        ),
    ]
