# Generated by Django 3.0.5 on 2020-05-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0066_remove_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpayment',
            name='GST_Tax',
            field=models.CharField(default='0', max_length=32),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Advance',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Balance',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Bill_Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.ShopHandlersSignUp'),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Card',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Card_Amount',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Card_Holder',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Cash',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Chit',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Chit_Amount',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Online_Amount',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Online_Transfer_UPI',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Payment_Mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online'), ('Cheque', 'Cheque')], default='Cash', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Previous_Balance',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Total_Balance',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.BillingItems'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-17'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-17'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-17', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-17'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-17'),
        ),
    ]
