# Generated by Django 3.0.5 on 2020-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0069_auto_20200518_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingpayment',
            name='Advance',
        ),
        migrations.RemoveField(
            model_name='billingpayment',
            name='Balance',
        ),
        migrations.RemoveField(
            model_name='billingpayment',
            name='Chit',
        ),
        migrations.RemoveField(
            model_name='billingpayment',
            name='Payment_Mode',
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-19'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-19'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-19', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-19'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-19'),
        ),
    ]
