# Generated by Django 3.0.5 on 2020-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0070_auto_20200519_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpayment',
            name='Total',
            field=models.CharField(blank=True, default='0', max_length=64, null=True),
        ),
    ]
