# Generated by Django 3.0.5 on 2020-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0071_auto_20200519_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitems',
            name='Discount',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='billingitems',
            name='GST_Tax',
            field=models.CharField(default='3', max_length=32),
        ),
    ]
