# Generated by Django 3.0.5 on 2020-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0072_auto_20200519_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitems',
            name='Discount',
            field=models.CharField(blank=True, default='0', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='billingitems',
            name='GST_Tax',
            field=models.CharField(blank=True, default='3', max_length=32, null=True),
        ),
    ]
