# Generated by Django 3.0.5 on 2020-05-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0073_auto_20200519_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitems',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='billingitems',
            name='GST_Tax',
        ),
    ]
