# Generated by Django 3.0.5 on 2020-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0074_auto_20200519_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpayment',
            name='Discount',
            field=models.CharField(blank=True, default='0', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='GST_Tax',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
    ]
