# Generated by Django 3.0.5 on 2020-05-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0075_auto_20200519_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpayment',
            name='Card',
            field=models.CharField(default='xxxx', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Card_Holder',
            field=models.CharField(default='xxxx', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='Online_Transfer_UPI',
            field=models.CharField(default='xxxx', max_length=64),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-20'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-20'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-20', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-20'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.DateField(default='2020-05-20'),
        ),
    ]
