# Generated by Django 3.0.5 on 2020-05-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0078_auto_20200524_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingpayment',
            name='Bill_Person',
        ),
        migrations.AddField(
            model_name='stockpaid',
            name='Payment',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-05-25', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-05-25'),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Amount_Paid',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Balance',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Date_Paid',
            field=models.CharField(default='[]', max_length=1024),
        ),
        migrations.AlterField(
            model_name='stockpaid',
            name='Metal_grams',
            field=models.CharField(default='[]', max_length=1024),
        ),
    ]
