# Generated by Django 3.0.5 on 2020-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0079_auto_20200525_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpaid',
            name='TotalBalance',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
