# Generated by Django 3.0.5 on 2020-05-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0084_auto_20200531_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldjewel',
            name='Amount',
            field=models.CharField(default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='oldjewel',
            name='weight_in_grams',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
