# Generated by Django 3.0.5 on 2020-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0085_auto_20200531_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpayment',
            name='CGST_Tax',
            field=models.CharField(blank=True, default='0.0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='GST_Tax',
            field=models.CharField(blank=True, default='0.0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='IGST_Tax',
            field=models.CharField(blank=True, default='0.0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingpayment',
            name='SGST_Tax',
            field=models.CharField(blank=True, default='0.0', max_length=32, null=True),
        ),
    ]
