# Generated by Django 3.0.5 on 2020-06-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0087_auto_20200601_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldjewel',
            name='Item',
            field=models.CharField(default='[]', max_length=2048),
        ),
        migrations.AddField(
            model_name='oldjewel',
            name='Total',
            field=models.CharField(default='[]', max_length=2048),
        ),
        migrations.AlterField(
            model_name='oldjewel',
            name='weight_in_grams',
            field=models.CharField(default='[]', max_length=2048),
        ),
    ]
