# Generated by Django 3.0.5 on 2020-06-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0088_auto_20200601_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldjewel',
            name='Amount',
            field=models.CharField(blank=True, default='0', max_length=16, null=True),
        ),
    ]
