# Generated by Django 3.0.5 on 2020-06-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0089_auto_20200601_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitems',
            name='Advance',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-06-10'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-06-10'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-06-10', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-06-10'),
        ),
    ]
