# Generated by Django 3.0.5 on 2020-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0090_auto_20200610_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitems',
            name='Advance',
        ),
        migrations.AddField(
            model_name='billingpayment',
            name='Advance',
            field=models.CharField(blank=True, default='0', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='End_Date',
            field=models.DateField(default='2020-06-11'),
        ),
        migrations.AlterField(
            model_name='chitbill',
            name='Start_Date',
            field=models.DateField(default='2020-06-11'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='Given_Date',
            field=models.CharField(default='2020-06-11', max_length=16),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Item_Type',
            field=models.CharField(choices=[('nethichuti', 'nethichuti'), ('Earring', 'Earring'), ('chain', 'chain'), ('Necklace', 'Necklace'), ('Aaram', 'Aaram'), ('Ottiyanam', 'Ottiyanam'), ('Ring', 'Ring'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Kaapu', 'Kaapu'), ('vangi', 'vangi'), ('Anklets', 'Anklets'), ('ArnaKayiru', 'ArnaKayiru'), ('Metti', 'Metti'), ('Mookuthi', 'Mookuthi')], default='Ring', max_length=32),
        ),
        migrations.AlterField(
            model_name='stockadd',
            name='Date',
            field=models.DateField(default='2020-06-11'),
        ),
    ]
